# Generated by rust2rpm 21
%bcond_without check

%global crate dura

Name:           rust-%{crate}
Version:        0.1.0
Release:        %autorelease
Summary:        You shouldn't ever lose your work if you're using Git

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            https://crates.io/crates/dura
Source:         %{crates_source}
# Initial patched metadata
Patch0:         dura-fix-metadata.diff

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging >= 21

%global _description %{expand:
You shouldn't ever lose your work if you're using Git.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE
%doc CONTRIBUTING.md README.md
%{_bindir}/dura

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/CONTRIBUTING.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

#%if %{with check}
#%check
#%cargo_test
#%endif

%changelog
%autochangelog
